# Generated by Django 4.2.18 on 2025-01-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Формат', 'verbose_name_plural': 'Форматы'},
        ),
    ]
