# Generated by Django 4.2.18 on 2025-01-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('manager', models.CharField(max_length=15)),
                ('invoice', models.CharField(blank=True, max_length=10, null=True)),
                ('client', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=50)),
                ('compound', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=10)),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('ril', models.PositiveIntegerField(blank=True, null=True)),
                ('ril2', models.PositiveIntegerField(blank=True, null=True)),
                ('ril3', models.PositiveIntegerField(blank=True, null=True)),
                ('workpiece_width', models.IntegerField()),
                ('workpiece_length', models.IntegerField()),
                ('stock', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('comment', models.TextField()),
                ('number_tk', models.CharField(blank=True, max_length=10, null=True)),
                ('shipping', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
